__Video resources__

* https://www.youtube.com/watch?v=ZBD9he4Zp1E
* https://www.youtube.com/watch?v=Npv180dQ_4Y
* https://www.youtube.com/watch?v=NqYY0PJbD3s



__Read this__
* http://csbio.unc.edu/mcmillan/Comp555S16/Lecture14.html
* https://www.cs.cmu.edu/~ckingsf/bioinfo-lectures/gaps.pdf
* http://www.bioinfo.rpi.edu/bystrc/courses/biol4540/lecture4.pdf

In [14]:
import pandas as pd
import numpy as np
def createScorMat(match = 1,mismatch = 0,nts = ['A','C','T','G']):
    """
    Create scoring matrix for nucleotides with a given match and mismatch values
    """
    scoringMatrix = np.zeros((len(nts),len(nts)),)
    np.fill_diagonal(scoringMatrix,match)
    scoringMatrix
    scoringMatrix[scoringMatrix == 0] = mismatch
    scoringMatrix = pd.DataFrame(scoringMatrix,index=nts,columns=nts)
    return scoringMatrix

#### Dynamic programming implementation
def scoringMatrix_local(x,y,subMat,indel):
    m = len(x) + 1
    n = len(y) + 1
    globMax = (0,0)
    scoringMat=np.zeros((n,m))
    for i in range(1,m):
        #print(x[i-1])
        for j in range(1,n):
            if x[i-1] == y[j-1]:
                #scoringMat[j-1][i-1] + subMat.loc[x[i-1]][y[j-1]]
                scoringMat[j][i] = scoringMat[j-1][i-1] + subMat.loc[x[i-1]][y[j-1]]
            else:
                mismatch = scoringMat[j-1][i-1] + subMat.loc[x[i-1]][y[j-1]]
                left = scoringMat[j-1][i] + indel
                up = scoringMat[j][i-1] + indel
                scoringMat[j][i] = max(mismatch,left,up,0)
            if scoringMat[j][i] >= scoringMat[globMax[1]][globMax[0]]:
                globMax = (i,j)
    return scoringMat,globMax


def scoringMatrix_global(x,y,subMat,indel):
    m = len(x) + 1
    n = len(y) + 1
    scoringMat=np.zeros((n,m))
    scoringMat[:][0] = [0] + list(np.cumsum([indel for _ in x]))
    scoringMat[:,0] = [0] + list(np.cumsum([indel for _ in y]))
    for i in range(1,m):
        #print(x[i-1])
        for j in range(1,n):
            if x[i-1] == y[j-1]:
                #scoringMat[j-1][i-1] + subMat.loc[x[i-1]][y[j-1]]
                scoringMat[j][i] = scoringMat[j-1][i-1] + subMat.loc[x[i-1]][y[j-1]]
            else:
                mismatch = scoringMat[j-1][i-1] + subMat.loc[x[i-1]][y[j-1]]
                left = scoringMat[j-1][i] + indel
                up = scoringMat[j][i-1] + indel
                scoringMat[j][i] = max(mismatch,left,up)
    return scoringMat


def backtrack_local(x,y,sm,maxLocs):
    i = maxLocs[0]
    j = maxLocs[1]
    w=''
    z=''
    z,w
    while i*j > 0:
        if x[i-1] == y[j-1]:
            w += x[i-1]
            z += y[j-1]
            i -= 1
            j -= 1
        else:
            left = sm[j-1][i]
            up = sm[j][i-1]
            diag = sm[j-1][i-1]
            whichmax = np.argmax([left,up,diag])
            if whichmax == 0:
                w += '-'
                z += y[j-1]
                j -= 1
            elif whichmax == 1:
                z += '-'
                w += x[i-1]
                i -= 1
            else:
                w += x[i-1]
                z += y[j-1]
                i -= 1
                j -= 1
        if sm[j][i] == 0:
            break
    return w[::-1],z[::-1]

def backtrack_global(x,y,sm,subMat,indel):
    i = len(x)
    j = len(y)
    w=''
    z=''
    z,w
    while i*j > 0:
        if x[i-1] == y[j-1]:
            w += x[i-1]
            z += y[j-1]
            i -= 1
            j -= 1
        else:
            left = sm[j-1][i] + indel
            up = sm[j][i-1] + indel
            diag = sm[j-1][i-1] + subMat.loc[x[i-1]][y[j-1]]
            whichmax = np.argmax([left,up,diag])
            if whichmax == 0:
                w += '-'
                z += y[j-1]
                j -= 1
            elif whichmax == 1:
                z += '-'
                w += x[i-1]
                i -= 1
            else:
                w += x[i-1]
                z += y[j-1]
                i -= 1
                j -= 1
    if j==0 and i>0:
        w = x[:i]+w[::-1]
        z = '-' * i + z[::-1]
    elif i==0 and j>0:
        z = y[:i]+z[::-1]
        w = '-' * j + w[::-1]
    else:
        w = w[::-1]
        z = z[::-1]
    return w,z

def locAl(x,y,subMat,indel):
    '''
    A wrapper for DP implementation of Smith-Waterman
    '''
    sm, maxLocs = scoringMatrix_local(x,y,subMat,indel)
    z,w = backtrack_local(x,y,sm,maxLocs)
    return z,w,sm[maxLocs[1],maxLocs[0]],sm

def globAl(x,y,subMat,indel):
    '''
    A wrapper for DP implementation of Smith-Waterman
    '''
    sm = scoringMatrix_global(x,y,subMat,indel)
    z,w = backtrack_global(x,y,sm,subMat,indel)
    return z,w,sm[len(y),len(x)]

def vizScoringMat(x,y,scoringMat):
    return pd.DataFrame(scoringMat,index=['']+[_ for _ in y],
             columns=['']+[_ for _ in x])

def readBlosum62():
    '''
    Read scoring matrix
    '''
    with open('blosum62.txt') as matrix_file:
        matrix = matrix_file.read()
        lines = matrix.strip().split('\n')

    blosum={}
    cols = lines[0].split()

    for row in lines[1:]:       
        idx = row[0]
        vals = row[1:].split()
        vals = [int(_) for _ in vals]
        #print(idx,vals)
        blosum[idx]=vals

    blosum = pd.DataFrame.from_dict(blosum,orient='index',columns=cols)
    return blosum

In [15]:
blosum = readBlosum62()

In [16]:
### Example from https://www.bioinformaticsalgorithms.org/bioinformatics-chapter-5
## Problem 3: Overlap Alignment
x='PRTEINS'
y='PRTWPSEIN'
indel = -8
subMat = blosum
locAl(x,y,subMat,indel)

('PRT',
 'PRT',
 17.0,
 array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  7.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0., 12.,  4.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  4., 17.,  9.,  1.,  0.,  1.],
        [ 0.,  0.,  0.,  9., 14.,  6.,  0.,  0.],
        [ 0.,  7.,  0.,  1.,  8., 11.,  4.,  0.],
        [ 0.,  0.,  6.,  1.,  1.,  6., 12.,  8.],
        [ 0.,  0.,  0.,  5.,  6.,  0.,  6., 12.],
        [ 0.,  0.,  0.,  0.,  2., 10.,  2.,  4.],
        [ 0.,  0.,  0.,  0.,  0.,  2., 16.,  8.]]))

In [17]:
### Example from https://www.bioinformaticsalgorithms.org/bioinformatics-chapter-5
## Problem 3: Overlap Alignment
x='ATTGACCTGA'
y='ATCCTGA'
indel = -1
gap = -1
subMat = createScorMat(match = 1,mismatch = -2,nts = list(set(y) | set(x)))
globAl(x,y,subMat,indel)

('ATTGACCTGA', 'A-T--CCTGA', 4.0)

In [18]:
### Example from https://www.bioinformaticsalgorithms.org/bioinformatics-chapter-5
## Problem 3: Overlap Alignment
x='PRTEINS'
y='PRTWPSEIN'
indel = -11
gap = -1
subMat = blosum
sm,_ = scoringMatrix_local(x,y,subMat,indel)
backtrack_local(x,y,sm,(len(x),len(y)))

('PRTEINS', 'PS-EIN-')

In [19]:
#http://csbio.unc.edu/mcmillan/Comp555S16/Lecture14.html
#http://rosalind.info/problems/ba5j/

In [22]:
### Example from https://www.bioinformaticsalgorithms.org/bioinformatics-chapter-5
## Problem 3: Overlap Alignment
x='ACACT'
y='AAT'
indel = -1
gap = -3
subMat = createScorMat(match = 1,mismatch = -1,nts = list(set(y) | set(x)))
globAl(x,y,subMat,indel),

(('ACACT', 'A-A-T', 1.0),)

In [23]:
def initScoringTable(x,y,initY=indel,initX=indel,start=0):
    m = len(x) + 1
    n = len(y) + 1
    scoringMat=np.zeros((n,m)) # Main scoring matrix
    scoringMat[:][0] = [0] + list(np.cumsum([initX for _ in x]))
    scoringMat[:,0] = [0] + list(np.cumsum([initY for _ in y]))
    scoringMat[0,0]=start
    return scoringMat

In [24]:
[-i + gap for i in range(1,n)]

[-4, -5]

In [25]:
gapExtension = -1
gapOpen = -3

### Follow this example 
https://www.youtube.com/watch?v=NqYY0PJbD3s

In [26]:
m= len(x)
n= len(y)

In [27]:
####
scoringMat=np.zeros((n,m)) # Main scoring matrix
inX = [gapOpen]
[inX.append(inX[i-1] + gapExtension) for i in range(1,m)]
scoringMat[:][0] = inX
scoringMat[:,0][1:] = [-np.inf  for i in range(1,n)]
scoringMat
scoringMat

array([[ -3.,  -4.,  -5.,  -6.,  -7.],
       [-inf,   0.,   0.,   0.,   0.],
       [-inf,   0.,   0.,   0.,   0.]])

In [28]:
####
scoringMat=np.zeros((n,m)) # Main scoring matrix
inY = [gapOpen]
[inY.append(inY[i-1] + gapExtension) for i in range(1,n)]
scoringMat[:,0] = inY
scoringMat[:][0][1:] = [-np.inf  for i in range(1,m)]
scoringMat

array([[ -3., -inf, -inf, -inf, -inf],
       [ -4.,   0.,   0.,   0.,   0.],
       [ -5.,   0.,   0.,   0.,   0.]])

In [29]:
inY = [gapOpen]
[inY.append(inY[i-1] + gapExtension) for i in range(1,m)]
inY

[-3, -4, -5, -6, -7]

In [30]:
def gapMatrix(x,y,initY=gap,initX=gap,start=0):
    m = len(x) + 1
    n = len(y) + 1
    scoringMat=np.zeros((n,m)) # Main scoring matrix
    scoringMat[:][0] = [0] + [-i + initX for i in range(1,m)]
    scoringMat[:,0] = [0] + [-i + initY for i in range(1,n)]
    scoringMat[0,0]=start
    return scoringMat

In [31]:
gapMatrix(x,y,-np.inf,gap,gap)

array([[ -3.,  -4.,  -5.,  -6.,  -7.,  -8.],
       [-inf,   0.,   0.,   0.,   0.,   0.],
       [-inf,   0.,   0.,   0.,   0.,   0.],
       [-inf,   0.,   0.,   0.,   0.,   0.]])

In [32]:
gapMatrix(x,y,gap,-np.inf,gap)

array([[ -3., -inf, -inf, -inf, -inf, -inf],
       [ -4.,   0.,   0.,   0.,   0.,   0.],
       [ -5.,   0.,   0.,   0.,   0.,   0.],
       [ -6.,   0.,   0.,   0.,   0.,   0.]])

#### Start here

In [42]:
x,y

('ACACT', 'AAT')

In [47]:
def gapMatrix(x,y,initY=gap,initX=gap,start=0):
    m = len(x) + 1
    n = len(y) + 1
    scoringMat=np.zeros((n,m)) # Main scoring matrix
    scoringMat[:][0] = [0] + [-i + initX for i in range(1,m)]
    scoringMat[:,0] = [0] + [-i + initY for i in range(1,n)]
    scoringMat[0,0]=start
    return scoringMat

def affineGapScoring(x,y,subMat,indel,gap):
    #### Initiate
    Mmatrix = gapMatrix(x,y,-np.inf,-np.inf,0)
    Ix = gapMatrix(x,y,gap,-np.inf,gap)
    Iy = gapMatrix(x,y,-np.inf,gap,gap)
    m= len(x)
    n= len(y)
    for j in range(1,n+1):
        for i in range(1,m+1):
            #### M matrix
            M = [Mmatrix[j-1,i-1] + subMat.loc[x[i-1]][y[j-1]],
                     Ix[j-1,i-1] + subMat.loc[x[i-1]][y[j-1]],
                     Iy[j-1,i-1] + subMat.loc[x[i-1]][y[j-1]]]
            Mmatrix[j,i] = max(M)

            #### Ix
            X = [Mmatrix[j-1,i] + gap + indel,
                 Ix[j-1,i] + indel]
            #### Iy
            Y = [Mmatrix[j,i-1] + gap + indel,
                 Iy[j,i-1] + indel]
            ###
            Ix[j,i] = max(X)
            Iy[j,i] = max(Y)
    return Mmatrix, Ix, Iy

def affineBacktrack(x,y,Mm,Ix,Iy):
    i = len(x)
    j = len(y)
    w=''
    z=''
    scoreMax = max([Mm[j,i],Mx[j,i],My[j,i]])
    while i*j > 0:
        print(i,j,w[::-1],z[::-1])
        if x[i-1] == y[j-1]:
            w += x[i-1]
            z += y[j-1]
            i -= 1
            j -= 1
        else:
            whichMax = np.argmax([Mm[j,i],Mx[j,i],My[j,i]])
            if whichMax == 0:
                w += x[i-1]
                z += y[j-1]
                i -= 1
                j -= 1
            elif  whichMax == 1:
                w += x[i-1]
                z += '-'
                i -= 1
            else:
                w += '-'
                z += y[j-1]
                j -= 1
    if j==0 and i>0:
        w = x[:i]+w[::-1]
        z = '-' * i + z[::-1]
    elif i==0 and j>0:
        z = y[:i]+z[::-1]
        w = '-' * j + w[::-1]
    else:
        w = w[::-1]
        z = z[::-1]
    return w,z,scoreMax

In [48]:
x='ACACT'
y='AAT'
gap = -3
indel = -1
subMat = createScorMat(match = 1,mismatch = -1,nts = list(set(y) | set(x)))

Mm, Mx, My = affineGapScoring(x,y,subMat,indel,gap)
w,z, sm = affineBacktrack(x,y,Mm,Mx,My)

#### Result
print(vizScoringMat(x,y,Mm))
print(vizScoringMat(x,y,Mx))
print(vizScoringMat(x,y,My))
print(w,z, sm)

5 3  
4 2 T T
3 1 CT AT
          A    C    A    C    T
   0.0 -inf -inf -inf -inf -inf
A -inf  1.0 -5.0 -4.0 -7.0 -8.0
A -inf -3.0  0.0 -2.0 -5.0 -6.0
T -inf -6.0 -4.0 -1.0 -3.0 -4.0
          A    C    A     C     T
  -3.0 -inf -inf -inf  -inf  -inf
A -4.0 -inf -inf -inf  -inf  -inf
A -5.0 -3.0 -9.0 -8.0 -11.0 -12.0
T -6.0 -4.0 -4.0 -6.0  -9.0 -10.0
          A     C    A    C    T
  -3.0 -4.0  -5.0 -6.0 -7.0 -8.0
A -inf -inf  -3.0 -4.0 -5.0 -6.0
A -inf -inf  -7.0 -4.0 -5.0 -6.0
T -inf -inf -10.0 -8.0 -5.0 -6.0
ACACT --AAT -4.0


In [49]:
x='PRTEINS'
y='PRTWPSEIN'
gap = -11
indel = -1
#subMat = createScorMat(match = 1,mismatch = -1,nts = list(set(y) | set(x)))
subMat = blosum

Mm, Mx, My = affineGapScoring(x,y,subMat,indel,gap)
w,z, sm = affineBacktrack(x,y,Mm,Mx,My)

#### Result
print(vizScoringMat(x,y,Mm))
print(vizScoringMat(x,y,Mx))
print(vizScoringMat(x,y,My))
print(w,z, sm)

7 9  
7 8 - N
6 7 S- IN
5 6 NS- EIN
4 5 INS- SEIN
3 4 EINS- PSEIN
2 4 TEINS- -PSEIN
1 4 RTEINS- --PSEIN
           P     R     T     E     I     N     S
   0.0  -inf  -inf  -inf  -inf  -inf  -inf  -inf
P -inf   7.0 -14.0 -14.0 -15.0 -18.0 -18.0 -18.0
R -inf -14.0  12.0  -6.0  -6.0 -10.0  -8.0 -10.0
T -inf -14.0  -6.0  17.0  -1.0  -2.0  -2.0  -2.0
W -inf -18.0  -9.0  -2.0  14.0   2.0   0.0   0.0
P -inf  -8.0  -9.0  -2.0   4.0  11.0   0.0   0.0
S -inf -17.0  -9.0  -1.0   4.0   2.0  12.0   4.0
E -inf -18.0  -9.0  -4.0   8.0   1.0   2.0  12.0
I -inf -21.0 -13.0  -5.0  -1.0  12.0  -2.0   0.0
N -inf -21.0 -11.0  -5.0   1.0  -4.0  18.0   1.0
            P     R     T     E     I     N     S
  -11.0  -inf  -inf  -inf  -inf  -inf  -inf  -inf
P -12.0  -inf  -inf  -inf  -inf  -inf  -inf  -inf
R -13.0  -5.0 -26.0 -26.0 -27.0 -30.0 -30.0 -30.0
T -14.0  -6.0   0.0 -18.0 -18.0 -22.0 -20.0 -22.0
W -15.0  -7.0  -1.0   5.0 -13.0 -14.0 -14.0 -14.0
P -16.0  -8.0  -2.0   4.0   2.0 -10.0 -12.0 -12.0
S -17.0

In [46]:
blosum['P']['P']

7

In [72]:
i,j

(3, 1)

In [65]:
i,j

(2, 0)

In [55]:
def make_matrix(sizex, sizey):
    """Creates a sizex by sizey matrix filled with zeros."""
    return [[0]*sizey for i in range(sizex)]

In [62]:
gap_start = -11
gap_ext = -1


M = make_matrix(len(x) + 1, len(y) + 1)
X = make_matrix(len(x) + 1, len(y) + 1)
Y = make_matrix(len(x) + 1, len(y) + 1)



for i in range(1, len(x)+1):
    M[i][0] = -np.Inf
    X[i][0] = -np.Inf
    Y[i][0] = gap_start + i * gap_ext
    
for i in range(1, len(y)+1):
    M[0][i] = -np.Inf
    X[0][i] = gap_start + i * gap_ext
    Y[0][i] = -np.Inf

In [63]:
M,X,Y

([[0, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
  [-inf, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  [-inf, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  [-inf, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  [-inf, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  [-inf, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  [-inf, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  [-inf, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
 [[0, -12, -13, -14, -15, -16, -17, -18, -19, -20],
  [-inf, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  [-inf, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  [-inf, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  [-inf, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  [-inf, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  [-inf, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  [-inf, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
 [[0, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
  [-12, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  [-13, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  [-14, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  [-15, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  [-16, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  [-17, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  [-18, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [70]:
x='ACACT'
y='AAT'
gap = -3
indel = -1
subMat = createScorMat(match = 1,mismatch = -1,nts = list(set(y) | set(x)))

In [71]:
for i in range(1, len(x)+1):
    for j in range(1, len(y)+1):

        M[i][j] = subMat.loc[x[i-1]][y[j-1]] + max(
                M[i-1][j-1],
                X[i-1][j-1],
                Y[i-1][j-1]
        )

        X[i][j] = max(
                gap_start + gap_ext + M[i][j-1],
                gap_ext + X[i][j-1],
                gap_start + gap_ext + Y[i][j-1]
        )

        Y[i][j] = max(
                gap_start + gap_ext + M[i-1][j],
                gap_start + gap_ext + X[i-1][j],
                gap_ext + Y[i-1][j]
        )

In [66]:
M,X,Y

([[0, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
  [-inf, 7, -14, -14, -18, -8, -17, -18, -21, -21],
  [-inf, -14, 12, -6, -9, -9, -9, -9, -13, -11],
  [-inf, -14, -6, 17, -2, -2, -1, -4, -5, -5],
  [-inf, -15, -6, -1, 14, 4, 4, 8, -1, 1],
  [-inf, -18, -10, -2, 2, 11, 2, 1, 12, -4],
  [-inf, -18, -8, -2, 0, 0, 12, 2, -2, 18],
  [-inf, -18, -10, -2, 0, 0, 4, 12, 0, 1]],
 [[0, -12, -13, -14, -15, -16, -17, -18, -19, -20],
  [-inf, -24, -5, -6, -7, -8, -9, -10, -11, -12],
  [-inf, -25, -17, 0, -1, -2, -3, -4, -5, -6],
  [-inf, -26, -18, -12, 5, 4, 3, 2, 1, 0],
  [-inf, -27, -19, -13, -7, 2, 1, 0, -1, -2],
  [-inf, -28, -20, -14, -8, -9, -1, -2, -3, 0],
  [-inf, -29, -21, -15, -9, -10, -11, 0, -1, -2],
  [-inf, -30, -22, -16, -10, -11, -12, -8, 0, -1]],
 [[0, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
  [-12, -24, -25, -26, -27, -28, -29, -30, -31, -32],
  [-13, -5, -17, -18, -19, -20, -21, -22, -23, -24],
  [-14, -6, 0, -12, -13, -14, -15, -16, -17, -18],
  [-15, 

In [68]:
opt = max(M[len(x)][len(y)], X[len(x)][len(y)], Y[len(x)][len(y)])
opt

6